name: Build

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: yarn install --frozen-lockfile
      - run: yarn svelte-kit sync
      - run: yarn build
